#Listas com materiais recicláveis 

materiais = [
    #PAPEL
  "papel sulfite",
  "papelão",
  "jornais",
  "revistas",
  "cadernos",
  "envelopes", 
  "papel branco",
  "cartolina",
  "caixa de ovos (papel)",
  "embalagens longa-vida (tetra pak)",
  "folhetos",
  "sacos de papel",
  "papel kraft",
  "caixa de pizza (sem gordura)",
  "papel de fax",
  "papel reciclado",
  "rótulos de papel",

  #PLÁSTICO
  "garrafa pet",
  "sacolas plásticas",
  "copos descartáveis",
  "embalagens de produtos de limpeza",
  "potes de alimentos",
  "tampas plásticas",
  "canudos",
  "filme plástico",
  "barbantes de nylon",
  "brinquedos de plástico",
  "escovas de dente",
  "tubos plásticos",
  "PVC",
  "PEAD",
  "PEBD",
  "PP",
  "PS",
  "acrílico",
  "embalagens de shampoo",
  "embalagens de cosméticos",

  # METAL
  "latas de alumínio",
  "latas de aço",
  "latinhas de refrigerante",
  "latinhas de cerveja",
  "tampas metálicas",
  "panelas sem cabo",
  "pregos e parafusos",
  "fios de cobre",
  "alumínio",
  "aço inox",
  "aerossóis vazios",
  "molhos e conservas (latas)",

    #VIDRO
  "garrafas de vidro",
  "potes de vidro",
  "copos de vidro",
  "frasco de perfume",
  "frasco de remédio (sem substância)",
  "vidros de conserva",
  "garrafas de bebidas",
  "tampas de vidro",

  #ELETRÔNICOS
  "celulares",
  "carregadores",
  "baterias",
  "pilhas recarregáveis",
  "televisores",
  "computadores",
  "teclados",
  "mouses",
  "tablets",
  "cabos",
  "placas-mãe",
  "fontes de alimentação"
]